# Generated by Django 3.2.9 on 2021-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211104_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
