# Generated by Django 3.2.9 on 2021-11-30 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211125_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_account_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
