# Generated by Django 3.2.9 on 2021-11-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
    ]
