version: "3"
   
services:
  db:
    image: postgres:10.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - db