# Generated by Django 3.2.9 on 2021-11-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20211120_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uid',
            new_name='id',
        ),
    ]
