# Generated by Django 3.2.9 on 2021-11-20 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_rename_uid_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
